---
# defaults file for common-prerequisite
repo_base_url: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
repo_gpg_keys:
  - https://packages.cloud.google.com/yum/doc/yum-key.gpg
  - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
